### ISSUE TITLE
Different webhooks per realm

### ISSUE THREAD

**Issue by pschichtel** [svenstaro/keycloak-http-webhook-provider#5]
This plugin seems to be almost what I'm looking for. I'd like to have different webhook destinations for different realms. To me it seems I can only configure the URL (and authentication) once in the jboss configuration and that's it.

In a perfect world I could configure this stuff in the keycloak UI, but apparently that is not as simple as I initially thought.

I could imagine namespacing the options in the Config.Scope to be `$realmName.serverUrl` and only if that doesn't exist check for `serverUrl` alone.

**Comment by svenstaro** [comment]
Oof yeah I might accept a clean implementation of what you want as a PR but I don't fancy doing that work myself.

**Comment by pschichtel** [comment]
I changed course in the mean time. I'll build a tiny go application as a "webhook router" and configure my keycloak globally to send webhooks to that proxy.

**Comment by svenstaro** [comment]
That's what we did as well. I think it's a cleaner and much simpler solution.

**Comment by pschichtel** [comment]
https://github.com/cubyte-oss/keycloak-http-webhook-provider/commit/c2b829b695bea87fe525c9deea6c5d116131f4fa

I simplified the plugin a bit:
* dropped authentication (not going to need that in my context)
* take the webhook url from env (makes containerized deployment simpler)
* add the realmId as an HTTP header

the latter allows me to use a plain nginx as a webhook router by using the header value as the input into a map lookup. In the nginx I could also add authentication if necessary:

```
map $http_x_keycloak_realm $webhook_target {
    realm-id http://webhook-url/;
}

server {
    listen       80;
    server_name  _;

    location /webhook {
        proxy_pass "$webhook_target";
    }
}

```

**Comment by svenstaro** [comment]
Thanks, though I suppose we should close this issue?
